- src/integrationTest/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerIT.java
- src/integrationTest/java/uk/gov/hmcts/reform/managecase/fixtures/WiremockFixtures.java
- src/main/java/uk/gov/hmcts/reform/managecase/client/datastore/CaseDetails.java
- src/main/java/uk/gov/hmcts/reform/managecase/domain/NoCRequestDetails.java
- src/main/java/uk/gov/hmcts/reform/managecase/service/noc/ChallengeAnswerValidator.java
- src/main/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestions.java
- src/main/java/uk/gov/hmcts/reform/managecase/service/noc/VerifyNoCAnswersService.java
- src/test/java/uk/gov/hmcts/reform/managecase/TestFixtures.java
- src/test/java/uk/gov/hmcts/reform/managecase/service/noc/ChallengeAnswerValidatorTest.java
- src/test/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestionsTest.java
- src/test/java/uk/gov/hmcts/reform/managecase/service/noc/VerifyNoCAnswersServiceTest.java
I would delete unwanted ES model classes and methods from repository layer in the next PR (clean-up).
https://tools.hmcts.net/jira/browse/ACA-126
Notice of change should not use Elastic Search to get the case
```
[ ] Yes
[ x] No
```
> ACA-126 - replaced internal ES call with external CaseDetailsById

- src/integrationTest/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerIT.java
- src/main/java/uk/gov/hmcts/reform/managecase/client/datastore/model/WizardPageComplexFieldOverride.java
- src/main/java/uk/gov/hmcts/reform/managecase/domain/AddressUK.java
- src/main/java/uk/gov/hmcts/reform/managecase/domain/OrganisationPolicy.java
- src/main/java/uk/gov/hmcts/reform/managecase/domain/PreviousOrganisation.java
- src/main/java/uk/gov/hmcts/reform/managecase/domain/PreviousOrganisationCollectionItem.java
- src/main/java/uk/gov/hmcts/reform/managecase/service/noc/ApplyNoCDecisionService.java
- src/main/resources/application.yaml
- src/test/java/uk/gov/hmcts/reform/managecase/service/noc/ApplyNoCDecisionServiceTest.java
[ACA-134](https://tools.hmcts.net/jira/browse/ACA-1334) _"Adjust PreviousOrganisation JSON format used by ApplyNoCDecision API (Phase 2A)"_
see also  [ACA-106](https://tools.hmcts.net/jira/browse/ACA-106) _"Update ApplyNoCDecision API (Phase 2A)"_
Adjust `PreviousOrganisation` JSON format returned by ApplyNoCDecision API after recent changes under [ACA-106](https://tools.hmcts.net/jira/browse/ACA-106), see #171.
```
[ ] Yes
[ ] No
```
> ACA-134 - Adjust ApplyNoCDecision API JSON output

- src/main/java/uk/gov/hmcts/reform/managecase/repository/DefaultDataStoreRepository.java
- src/main/java/uk/gov/hmcts/reform/managecase/util/JacksonUtils.java
- src/test/java/uk/gov/hmcts/reform/managecase/repository/DataStoreRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/managecase/util/JacksonUtilsTest.java
https://tools.hmcts.net/jira/browse/RDM-11407
Json merge has some issue dealing with nulls in NestedField in COR object. 
Options: 
1. We could you actually replace whole COR field ([commit](https://github.com/hmcts/aac-manage-case-assignment/pull/246/commits/d2d2b800ce7bcc83d897a6c2858e0d0706e06ef6) )
2. Fix the ordering of merge params and null check ([commit2](https://github.com/hmcts/aac-manage-case-assignment/pull/246/commits/47e6c2e47b5a3e9c12a61e04a157fdec82dfe1e4) [commit3](https://github.com/hmcts/aac-manage-case-assignment/pull/246/commits/bb698a2d9db015353fb1f1bc88ee6a90fad29bc2)
3. Not implemented - > we can actual set NULL for "OrganisationToAdd" and "OrganisationToRemove" after apply-noc-decision like [here](https://github.com/hmcts/aac-manage-case-assignment/blob/master/src/ …
> RDM-11407 - fixing COR field merge

- build.gradle
- src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201 - Assign Access within Organisation.feature
- src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201-Base-useUserToken.td.json
- src/functionalTest/resources/features/F-201 - Assign Access within Organisation/S-201.1b.td.json
- src/functionalTest/resources/features/F-201 - Assign Access within Organisation/S-201.2b.td.json
- src/integrationTest/java/uk/gov/hmcts/reform/managecase/fixtures/WiremockFixtures.java
- src/main/java/uk/gov/hmcts/reform/managecase/api/controller/CaseAssignmentController.java
- src/main/java/uk/gov/hmcts/reform/managecase/client/datastore/DataStoreApiClient.java
- src/main/java/uk/gov/hmcts/reform/managecase/repository/DataStoreRepository.java
- src/main/java/uk/gov/hmcts/reform/managecase/repository/DefaultDataStoreRepository.java
- src/main/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentService.java
- src/main/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestions.java
- src/main/java/uk/gov/hmcts/reform/managecase/service/noc/RequestNoticeOfChangeService.java
- src/test/java/uk/gov/hmcts/reform/managecase/api/controller/CaseAssignmentControllerTest.java
- src/test/java/uk/gov/hmcts/reform/managecase/repository/DataStoreRepositoryTest.java
- src/test/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentServiceTest.java
- src/test/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestionsTest.java
- src/test/java/uk/gov/hmcts/reform/managecase/service/noc/RequestNoticeOfChangeServiceTest.java
https://tools.hmcts.net/jira/browse/ACA-147
Update the assign access operation to use invoking user instead of the system user for fetching the case data. Previously a bug identified where the system user has been used with the caseworker-caa role, who had no access to the case data. 
```
[ ] Yes
[X ] No
```
> ACA-147 Update Assign access - switch from system to invoking user

- src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/CCD-1236
Changed [cache strategy](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/2.2.2/com/github/benmanes/caffeine/cache/Caffeine.html#expireAfterWrite-long-java.util.concurrent.TimeUnit-) from `expireAfterAccess` to `expireAfterWrite` as static Idam system user tokens must expire always after certain period. 
```
[ ] Yes
[ x] No
```
> CCD-1236 - changed cache strategy

- config/owasp/suppressions.xml
CCD-1322 (https://tools.hmcts.net/jira/browse/CCD-1322)
Updated CVE suppression dates in suppressions.xml to 25/07/2021
```
[ ] Yes
[x] No
```
> CCD-1322: Updated CVE suppression dates

- config/owasp/suppressions.xml
N/A
- Added suppression entries to suppressions.xml for CVE-2020-23171, 2021-22119 and CVE-2021-28170.  These will be removed when CVEs are addressed.
```
[ ] Yes
[x] No
```
> Added suppression entries for three CVEs

- config/owasp/suppressions.xml
CCD-1331 (https://tools.hmcts.net/jira/browse/CCD-1331)
Updated CVE suppression dates in suppressions.xml file to 25/09/2021.  The three remaining entries in this file are flagged as false positives so no additional resolution work required.
```
[ ] Yes
[x] No
```
> Updated CVE suppression dates to 25/09/2021.

- build.gradle
- config/owasp/suppressions.xml
CCD-1855 (https://tools.hmcts.net/jira/browse/CCD-1855)
- Updated spring-security version in build.gradle to 5.4.7 to resolve CVE-2021-22119
```
[ ] Yes
[x] No
```
> Ccd 1855 CVE 2021 22119

- build.gradle
- config/owasp/suppressions.xml
CCD-1851 (https://tools.hmcts.net/jira/browse/CCD-1851)
Changed build.gradle to explicitly specify version of jakarta.el to use.
This will resolve CVE-2021-28170.
Removed CVE-2021-28170 entry from suppressions.xml
```
[ ] Yes
[x] No
```
> CCD-1851: Resolve CVE-2021-28170

- build.gradle
- config/owasp/suppressions.xml
CCD-2110 (https://tools.hmcts.net/jira/browse/CCD-2110)
- Updated dependencyManagement section of build.gradle. Set version of org.apache.tomcat.embed group to 9.0.54 to resolve CVE-2021-42340.
- Removed suppression of CVE-2021-42340 from suppressions.xml
```
[ ] Yes
[x] No
```
> CCD-2110: Address CVE-2021-42340

- build.gradle
- config/owasp/suppressions.xml
CCD-2133 (https://tools.hmcts.net/jira/browse/CCD-2133)
- Updated build.gradle.  Set value of override of spring-framework.version property to 5.3.12 to address CVE-2021-22096.
- Removed temporary suppression of CVE-2021-22096 from suppressions.xml
```
[ ] Yes
[x] No
```
> CCD-2133: Address CVE-2021-22096

- config/owasp/suppressions.xml
CCD-2107 (https://tools.hmcts.net/jira/browse/CCD-2107)
Updated CVE suppression dates in suppressions.xml to 25/12/2021.
```
[ ] Yes
[x] No
```
> CCD-2107: Updated CVE suppression dates

- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2231
Changed suppression dates from 2021-12-25 to 2022-01-25
```
[ ] Yes
[X] No
```
> CCD-2231-update-cve-suppression-dates-dec-2021

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3092
Upgrading framework to 5.3.19 due to this vulnerability:
In Spring Framework versions 5.3.0 - 5.3.18, 5.2.0 - 5.2.20, and older unsupported versions, the patterns for disallowedFields on a DataBinder are case sensitive which means a field is not effectively protected unless it is listed with both upper and lower case for the first character of the field, including upper and lower case for the first character of all nested fields within the property path.
```
[ ] Yes
[ x] No
```
> CVE-2022-22968 : aac-manage-case-assignment fix

- config/owasp/suppressions.xml
The package com.google.code.gson:gson before 2.8.9 are vulnerable to Deserialization of Untrusted Data via the writeReplace() method in internal classes, which may lead to DoS attacks.
CWE-502 Deserialization of Untrusted Data.
```
[ ] Yes
[ x] No
```
> CVE-2022-25647 : suppression change

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3267
Upgrading tomcat version to 9.0.63.
The documentation of Apache Tomcat 10.1.0-M1 to 10.1.0-M14, 10.0.0-M1 to 10.0.20, 9.0.13 to 9.0.62 and 8.5.38 to 8.5.78 for the EncryptInterceptor incorrectly stated it enabled Tomcat clustering to run over an untrusted network. This was not correct
```
[ ] Yes
[ x] No
```
> CVE-2022-29885: aac-manage-case-assignment fix

- build.gradle
CCD-3297 (https://tools.hmcts.net/jira/browse/CCD-3297)
Added junit formatter plugin to doLast section of smoke and functional test tasks.  This causes test result XML files to be created in the locations expected by the smoke and functional stages of the pipeline.  These locations were recently corrected under DTSPO-6817.
```
[ ] Yes
[x] No
```
> CCD-3297: Added junit formatter to smoke and functional test tasks

- src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201 - Assign Access within Organisation.feature
- src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201_S2_Querying_No_Access_Over_C1.td.json
- src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201_S2_Querying_Their_Access_Over_C1.td.json
- src/functionalTest/resources/features/F-202 - Get Assignments in My Organisation/F-202 - Get Assignments in My Organisation.feature
- src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203 - Unassign Access Within Organisation.feature
- src/functionalTest/resources/features/F-209 - Apply NoC Decision/AccessAssignment/F-209.6_Delete_Creator_Role.td.json
- src/functionalTest/resources/features/F-209 - Apply NoC Decision/AccessAssignment/F-209_Assign_Access_Base.td.json
- src/functionalTest/resources/features/F-209 - Apply NoC Decision/AccessAssignment/F-209_Delete_Creator_Role.td.json
- src/functionalTest/resources/features/F-209 - Apply NoC Decision/AccessAssignment/F-209_GET_Case_Access_Base.td.json
- src/functionalTest/resources/features/F-209 - Apply NoC Decision/AccessAssignment/F-209_GET_Case_Access_Richard_Assigned.td.json
- src/functionalTest/resources/features/F-209 - Apply NoC Decision/AccessAssignment/F-209_GET_Case_Access_Richard_NOT_Assigned.td.json
- src/functionalTest/resources/features/common/data-store/AccessAssignment/Assign_Case_Access__Base.td.json
- src/functionalTest/resources/features/common/data-store/AccessAssignment/Delete_Case_Access__Base.td.json
- src/functionalTest/resources/features/common/data-store/AccessAssignment/Get_Case_Access__Base.td.json
- src/functionalTest/resources/features/common/data-store/Prerequisite_Case_Creation_C0_Without_Org_Policies.td.json
- src/functionalTest/resources/features/common/response/Case_Found.td.json
- src/functionalTest/resources/features/common/response/Case_Not_Found.td.json
[CCD-3588](https://tools.hmcts.net/jira/browse/CCD-3588) _"AAC API in production failing-returns 502 for sols who are attempting to share a case in exui"_
Reenable the FTAs that are dissabled due to:
* missing the SearchCriteria property introduced for GlobalSearch.
* after 404 response change from data-stores get-case API.
> NB: this PR is based off #425 and is dependent on hmcts/ccd-data-store-api#2064
```
[ ] Yes
[x] No
```
> CCD-3588 FTA patch

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3426
CVE-2022-34305 tomcat upgrade 9.0.65
```
[ ] Yes
[ x] No
```
> CCD-3426 CVE-2022-34305 tomcat upgrade 9.0.65, suppression removed

- Jenkinsfile_CNP
- build.gradle
- config/owasp/suppressions.xml
[CCD-4035](https://tools.hmcts.net/jira/browse/CCD-4035) _"Expand aac-manage-case-assigment FTs to cover new CreatedBy field"_
This is a patch to #455.
* Adjust cucumber configuration in `build.gradle` to allow optional skip of `@callbackTests` without failing tests.
```
[ ] Yes
[x] No
```
> CCD-4035 PATCH to existing PR #455

- Jenkinsfile_CNP
- build.gradle
- infrastructure/aat.tfvars
- infrastructure/demo.tfvars
- infrastructure/ithc.tfvars
- infrastructure/main.tf
- infrastructure/perftest.tfvars
- infrastructure/prod.tfvars
- infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-15408
Removes old identity from code after  https://github.com/hmcts/aac-manage-case-assignment/pull/497
tfvars files just removed as they only contained these MI references
```
[ ] Yes
[ ] No
```
> Clean up old MI from code

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5185
Fix CVE-2023-34034 : bump spring-security.version to 5.7.11
```
[ ] Yes
[ x] No
```
> Fix CVE-2023-34034 : bump spring-security.version to 5.7.11

- build.gradle
- config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5160
CCD-5160 : Fix CVE-2023-35116 : bumped jackson.version to 2.16.0
```
[ ] Yes
[x ] No
```
> CCD-5160 : Fix CVE-2023-35116 : bumped jackson.version to 2.16.0

- charts/aac-manage-case-assignment/Chart.yaml
Will stop downstream apps relying on this being stuck by this fixed bug https://github.com/hmcts/chart-library/pull/118/files which was released in 5.0.4 of java
```
[ ] Yes
[ ] No
```
> Update java chart dependency
