Jenkinsfile_CNP, build.gradle, charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/requirements.yaml, charts/aac-manage-case-assignment/values.preview.template.yaml, charts/aac-manage-case-assignment/values.yaml, config/owasp/suppressions.xml, gradle/wrapper/gradle-wrapper.properties, infrastructure/main.tf, src/integrationTest/java/uk/gov/hmcts/reform/managecase/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/managecase/TestIdamConfiguration.java, src/integrationTest/java/uk/gov/hmcts/reform/managecase/config/SwaggerPublisher.java, src/integrationTest/java/uk/gov/hmcts/reform/managecase/controllers/GetWelcomeTest.java, src/integrationTest/resources/integration-test.properties, src/integrationTest/resources/wiremock-stubs/_idam_default.json, src/main/java/uk/gov/hmcts/reform/managecase/ApplicationParams.java, src/main/java/uk/gov/hmcts/reform/managecase/config/AuthClientConfiguration.java, src/main/java/uk/gov/hmcts/reform/managecase/config/CacheConfiguration.java, src/main/java/uk/gov/hmcts/reform/managecase/config/SecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/managecase/security/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/managecase/security/JwtGrantedAuthoritiesConverter.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml, src/test/java/uk/gov/hmcts/reform/managecase/security/IdamRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/managecase/security/JwtGrantedAuthoritiesConverterTest.java
https://tools.hmcts.net/jira/browse/RDM-8529
Integration for 
- IDAM authentication
- S2S authentication
- ccd-data-store-api
- PRD
```
[ ] Yes
[ x] No
```
=> RDM-8529 - external functional components integration

.gitignore, Jenkinsfile_CNP, README.md, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/managecase/befta/ManageCaseBeftaMain.java, src/functionalTest/java/uk/gov/hmcts/reform/managecase/befta/ManageCaseTestAutomationAdapter.java, src/functionalTest/resources/features/F-000/F-000.feature, src/functionalTest/resources/features/F-000/S-000.td.json, src/functionalTest/resources/features/common/response/header/Common_200_Response_Headers.td.json, src/functionalTest/resources/features/common/response/header/Common_Response_Headers.td.json
[RDM-8530](https://tools.hmcts.net/jira/browse/RDM-8530) - _Manage Case Assignment - BEFTA integration_
* Register BEFTA framework and add initial sample test for health endpoint
* Suppress Java 11 illegal reflective access warnings from BEFTA framework
* Bump PMD version number to remove XPath deprecated attribute warnings.
```
[ ] Yes
[x] No
```
=> RDM-8530 - BEFTA integration

.github/workflows/swagger.yml, Jenkinsfile_CNP, build.gradle, charts/aac-manage-case-assignment/values.preview.template.yaml, charts/aac-manage-case-assignment/values.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/features/F-000/S-000.td.json, src/integrationTest/java/uk/gov/hmcts/reform/managecase/BaseTest.java, src/integrationTest/java/uk/gov/hmcts/reform/managecase/api/controller/CaseAssignmentControllerIT.java, src/integrationTest/java/uk/gov/hmcts/reform/managecase/api/controller/ZuulProxyDataStoreRequestIT.java, src/integrationTest/java/uk/gov/hmcts/reform/managecase/fixtures/WiremockFixtures.java, src/integrationTest/resources/integration-test.properties, src/integrationTest/resources/wiremock-stubs/idam/token.json, src/main/java/uk/gov/hmcts/reform/managecase/Application.java, src/main/java/uk/gov/hmcts/reform/managecase/ApplicationParams.java, src/main/java/uk/gov/hmcts/reform/managecase/repository/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/managecase/security/SecurityUtils.java, src/main/java/uk/gov/hmcts/reform/managecase/zuulfilters/AllowedUrlRoutingFilter.java, src/main/java/uk/gov/hmcts/reform/managecase/zuulfilters/AuthHeaderRoutingFilter.java, src/main/java/uk/gov/hmcts/reform/managecase/zuulfilters/UrlWhitelistRoutingFilter.java, src/main/resources/application.yaml, src/main/resources/bootstrap.yaml
https://tools.hmcts.net/jira/browse/ACA-6
Introduce Zuul to proxy requests to data store.
```
[ ] Yes
[ x] No
```
=> ACA-6 Zuul proxy

aca-docker/mocks/wiremock/__files/prd_users.json, aca-docker/mocks/wiremock/mappings/organisation-users.json, build.gradle, charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.preview.template.yaml, charts/aac-manage-case-assignment/values.yaml, src/integrationTest/java/uk/gov/hmcts/reform/managecase/api/controller/CaseAssignmentControllerIT.java, src/integrationTest/java/uk/gov/hmcts/reform/managecase/fixtures/WiremockFixtures.java, src/integrationTest/resources/integration-test.properties, src/main/java/uk/gov/hmcts/reform/managecase/client/prd/PrdApiClient.java, src/main/java/uk/gov/hmcts/reform/managecase/client/prd/ProfessionalUser.java, src/main/java/uk/gov/hmcts/reform/managecase/repository/DefaultPrdRepository.java, src/main/java/uk/gov/hmcts/reform/managecase/repository/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/managecase/TestFixtures.java, src/test/java/uk/gov/hmcts/reform/managecase/repository/IdamRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/managecase/repository/PrdRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentServiceTest.java
ACA-46
Performance improvement around getting user roles
```
[ ] Yes
[X] No
```
=> ACA- 46-  Performance Improvement for Assign Access within Organisation

aca-docker/bin/users.json, aca-docker/mocks/wiremock/__files/prd_users.json
--
Fix spelling inconsistency in user emails
```
[X] Yes
[ ] No
```
=> Fix user emails

Jenkinsfile_CNP
=> pointing to aat of downstream dependencies for tests

Jenkinsfile_CNP, charts/aac-manage-case-assignment/values.aat.template.yaml
=> Master FT fixes - pointing to staging of ccd-data-store api until case-users api available

.gitignore, Jenkinsfile_CNP, build.gradle, src/functionalTest/resources/features/F-000/S-000.td.json
https://tools.hmcts.net/jira/browse/RDM-9342
```
[ ] Yes
[ ] No
```
=> RDM-9342: Alter smoke and functional tests to present separate reports

config/owasp/suppressions.xml, src/integrationTest/java/uk/gov/hmcts/reform/managecase/api/controller/CaseAssignmentControllerIT.java, src/integrationTest/java/uk/gov/hmcts/reform/managecase/fixtures/WiremockFixtures.java, src/main/java/uk/gov/hmcts/reform/managecase/repository/IdamRepository.java, src/main/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentService.java, src/main/resources/application.yaml, src/test/java/uk/gov/hmcts/reform/managecase/repository/IdamRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentServiceTest.java
https://tools.hmcts.net/jira/browse/ACA-95
```
[ ] Yes
[ ] No
```
=> Replaced idam searchUsers api with getUserByUserId

build.gradle
=> degrading befta-fw to 5.1.0 without Noc

build.gradle
=> forcing groovy version to inline with rest-assured

Jenkinsfile_CNP, charts/aac-manage-case-assignment/values.aat.template.yaml
=> Build fix - removed staging pod reference as it should be aat

src/integrationTest/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerIT.java
=> ACA-101: Write integration tests for set org to remove

Jenkinsfile_CNP, charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/ACA-108
Add "finrem_case_orchestration" to S2S allowed list
```
[ ] Yes
[ x] No
```
=> Add "finrem_case_orchestration" to S2S allowed list

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/ACA-123
Fix All Recent CVEs in All CCD Apps
```
[ ] Yes
[X] No
```
=> ACA-123 Fix All Recent CVEs in MCA Application

Jenkinsfile_CNP, build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10549
Fix CVEs Newly Reported on All 4 Java Apps
```
[ ] Yes
[X] No
```
=> RDM-10549 Fix CVEs Newly Reported on All 4 Java Apps

src/functionalTest/resources/features/F-208 - Set Organisation To Remove/S-208.1.td.json, src/functionalTest/resources/features/F-208 - Set Organisation To Remove/S-208.5.td.json, src/functionalTest/resources/features/F-208 - Set Organisation To Remove/S-208.6.td.json, src/functionalTest/resources/features/F-208 - Set Organisation To Remove/S-208.7.td.json
=> ACA-87: Fix issue in FTA with case role id field

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10678
[20.4&20.5] Regular CI Maintenance
```
[ ] Yes
[X] No
```
=> RDM-10678 added suppressions

Jenkinsfile_CNP, charts/aac-manage-case-assignment/values.preview.template.yaml
Change NoC branch to point to the develop builds of definition-store and data-store
```
[ ] Yes
[X] No
```
=> Point NOC branch back to develop PR builds of def-store and data-store

src/functionalTest/resources/features/F-204 - Get NoC Questions/S-204.6.td.json, src/main/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeController.java, src/test/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerTest.java
=> Updated swagger to inline with code.

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-10809
fix newly reported CVE's in AAC manage case assignment
```
[ ] Yes
[X] No
```
=> RDM-10809 fix newly reported CVE's in AAC manage case assignment

charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml
=> RDM-10908: added Divorce service to whitelist for Assign Case Access

src/main/java/uk/gov/hmcts/reform/managecase/config/JacksonObjectMapperConfig.java
https://tools.hmcts.net/jira/browse/ACA-136
Disable Jackson ObjectMapper failing on unknown properties
```
[ ] Yes
[x] No
```
=> ACA-136 - Disable failing on unknown properties

charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml
=> RDM_10980: whitelisted divorce_frontend

charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml
=> RDM-10908: whitelisting divorce_frontend

src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201 - Assign Access within Organisation.feature, src/functionalTest/resources/features/F-201 - Assign Access within Organisation/S-201.6.td.json, src/functionalTest/resources/features/F-201 - Assign Access within Organisation/S-201.6a.td.json, src/functionalTest/resources/features/F-201 - Assign Access within Organisation/S-201.6b.td.json, src/integrationTest/java/uk/gov/hmcts/reform/managecase/api/controller/CaseAssignmentControllerIT.java, src/main/java/uk/gov/hmcts/reform/managecase/security/SecurityUtils.java, src/main/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentService.java, src/main/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestions.java, src/main/java/uk/gov/hmcts/reform/managecase/service/noc/PrepareNoCService.java, src/main/java/uk/gov/hmcts/reform/managecase/service/noc/RequestNoticeOfChangeService.java, src/test/java/uk/gov/hmcts/reform/managecase/security/SecurityUtilsTest.java, src/test/java/uk/gov/hmcts/reform/managecase/service/CaseAssignmentServiceTest.java, src/test/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestionsTest.java, src/test/java/uk/gov/hmcts/reform/managecase/service/noc/PrepareNoCServiceTest.java, src/test/java/uk/gov/hmcts/reform/managecase/service/noc/RequestNoticeOfChangeServiceTest.java
https://tools.hmcts.net/jira/browse/ACA-137
```
[ ] Yes
[ ] No
```
=> ACA 137: Ability to identify the Jurisdiction of a Solicitor

charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml
=> IAC whitelisting for Share a Case

infrastructure/main.tf
=> Update KV TF to master

Jenkinsfile_CNP, config/owasp/suppressions.xml, src/main/java/uk/gov/hmcts/reform/managecase/api/errorhandling/RestExceptionHandler.java
=> pointing to TEST_URL

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11434
CVE-2021-22112 (AAC Manage Case Assignment)
```
[ ] Yes
[X] No
```
=> RDM-11434 CVE-2021-22112 (AAC Manage Case Assignment)

src/main/java/uk/gov/hmcts/reform/managecase/domain/DynamicList.java, src/main/java/uk/gov/hmcts/reform/managecase/domain/DynamicListElement.java, src/test/java/uk/gov/hmcts/reform/managecase/util/JacksonUtilsTest.java
https://tools.hmcts.net/jira/browse/RDM-11434
CVE-2021-22112 (AAC Manage Case Assignment) Sonarqube issues
```
[ ] Yes
[X] No
```
=> RDM-11434 CVE-2021-22112 Fixing sonarqube issues

build.gradle
https://tools.hmcts.net/jira/browse/ACA-143
Address Sonar Failures on the master pipeline
```
[ ] Yes
[X] No
```
=> ACA-143 exclude file from sonarqube analysis

src/main/java/uk/gov/hmcts/reform/managecase/api/errorhandling/RestExceptionHandler.java, src/test/java/uk/gov/hmcts/reform/managecase/repository/DataStoreRepositoryTest.java, src/test/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestionsTest.java, src/test/java/uk/gov/hmcts/reform/managecase/util/JacksonUtilsTest.java
https://tools.hmcts.net/jira/browse/ACA-143
Address Sonar Failures on the master pipeline
```
[ ] Yes
[X] No
```
=> ACA-143 added some unit tests

aca-docker/compose/aca.yml, build.gradle, src/main/resources/application.yaml
[RDM-11416](https://tools.hmcts.net/jira/browse/RDM-11416)
Stop `aca-wiremock` port clashing with `case-document-am-api` port
```
[ ] Yes
[X] No
```
=> RDM-11416 - Avoid port clashes

src/main/java/uk/gov/hmcts/reform/managecase/api/errorhandling/CaseIdLuhnException.java, src/main/java/uk/gov/hmcts/reform/managecase/api/errorhandling/RestExceptionHandler.java, src/test/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerTest.java, src/test/java/uk/gov/hmcts/reform/managecase/service/noc/NoticeOfChangeQuestionsTest.java
https://tools.hmcts.net/jira/browse/RDM-11416
Fix code coverage issues raised in Sonarqube after previous PR for RDM-11416 was merged
```
[ ] Yes
[X] No
```
=> Rdm 11416 - Fix code coverage

Jenkinsfile_CNP, charts/aac-manage-case-assignment/values.preview.template.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-11765
Update CVE Suppress Until Date In All Services
```
[ ] Yes
[X] No
```
=> RDM-11765 Update CVE Suppress Until Date In All Services

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-12131
Extend Expiry Dates of All CVE Suppressions in CCD Repos
```
[ ] Yes
[X] No
```
=> RDM-12131 Extend Expiry Dates of All CVE Suppressions in CCD Repos

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/RDM-12204
CVE-2021-29425 (AAC manage case assignment)
```
[ ] Yes
[X] No
```
=> RDM-12204 CVE-2021-29425 (AAC manage case assignment)

charts/aac-manage-case-assignment/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-808?filter=-1
Upgrade Base Chart Versions (Java & Nodejs)
```
[ ] Yes
[X] No
```
=> Ccd 808 Upgrade Base Chart Versions

charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml
https://tools.hmcts.net/jira/browse/CCD-998
```
[ ] Yes
[ ] No
```
=> CCD-998 add fpl_case_service

build.gradle
https://tools.hmcts.net/jira/browse/RDM-9765
Bump up BEFTA Fw version for RDM-9765.
```
[ ] Yes
[X] No
```
=> RDM-9765 Added jit pack & befta code changes

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1219
```
[ ] Yes
[X] No
```
=> CCD-1219 : Updated CVE suppress until date by 1 month

build.gradle, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/managecase/befta/ManageCaseAssignmentTestAutomationAdapter.java
https://tools.hmcts.net/jira/browse/CCD-1245
migrate to ccd definitions for functional test automations
```
[ ] Yes
[X] No
```
=> migrate to ccd definitions for functional test automations

src/functionalTest/java/uk/gov/hmcts/reform/managecase/befta/ManageCaseAssignmentTestAutomationAdapter.java
=> fix merge conflict resolution issue

src/functionalTest/java/uk/gov/hmcts/reform/managecase/befta/ManageCaseAssignmentTestAutomationAdapter.java
=> fix broken build resolving conflicts

build.gradle, src/test/java/uk/gov/hmcts/reform/managecase/api/controller/NoticeOfChangeControllerTest.java
https://tools.hmcts.net/jira/browse/CCD-1276
CVE-2021-22118 in AAC Manage Case Assignment
```
[ ] Yes
[x] No
```
=> CCD-1276 CVE-2021-22118 in AAC Manage Case Assignment

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-1246
CVE-2021-22112 (Manage Case Assignment)
```
[ ] Yes
[x] No
```
=> CCD-1246 CVE-2021-22112 (AAC Manage Case Assignment)

build.gradle
https://tools.hmcts.net/jira/browse/CCD-1656
https://tools.hmcts.net/jira/browse/CCD-1657
Fix 2 actionable CVEs
```
[ ] Yes
[X] No
```
=> Fix 2 actionable CVEs

Jenkinsfile_nightly, build.gradle, config/fortify-client.properties
https://tools.hmcts.net/jira/browse/CCD-1608
```
[ ] Yes
[X] No
```
=> CCD-1608 : Fortify Scan implementation for aac-manage-case-assignment

Jenkinsfile_nightly
Add CRON schedule to trigger nightly piplines
```
[ ] Yes
[x] No
```
=> CCD-1691 CRON schedule to trigger nightly build

config/owasp/suppressions.xml, src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201 - Assign Access within Organisation.feature, src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201_Case_Found.td.json, src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201_Case_Not_Found.td.json, src/functionalTest/resources/features/common/data-store/Case_Creation.td.json
=> RDM-12423 Improve Grant Assign Access FTAs

charts/aac-manage-case-assignment/Chart.yaml
CCD-1711
```
[ ] Yes
[x] No
```
=> Update Chart.yaml Java -> 3.6.0

config/owasp/suppressions.xml
N/A
Updated CVE suppression dates in suppressions.xml to 25/10/2021
```
[ ] Yes
[x] No
```
=> Updated CVE suppression dates to 25/10/2021

build.gradle, src/functionalTest/resources/features/F-201 - Assign Access within Organisation/F-201 - Assign Access within Organisation.feature, src/functionalTest/resources/features/F-202 - Get Assignments in My Organisation/F-202 - Get Assignments in My Organisation.feature, src/functionalTest/resources/features/F-203 - Unassign Access Within Organisation/F-203 - Unassign Access Within Organisation.feature, src/functionalTest/resources/features/F-206 - Request Notice Of Change/F-206 - Request Notice Of Change.feature, src/functionalTest/resources/features/F-207 - Check Notice Of Change Approval/F-207 - Check Notice Of Change Approval.feature
https://tools.hmcts.net/jira/browse/CCD-2344
Ignore failed functional tests
```
[ ] Yes
[X] No
```
=> Fix functional tests in master build

src/functionalTest/resources/features/F-205 - Validate NoC Questions/F-205.feature, src/functionalTest/resources/features/F-206 - Request Notice Of Change/F-206 - Request Notice Of Change.feature
https://tools.hmcts.net/jira/browse/CCD-2344
Ignore failing tests
```
[ ] Yes
[x] No
```
=> Ignore failing tests in master build

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2357
Amending suppression dates by 1 month
```
[ ] Yes
[ X] No
```
=> Amending suppression dates by 1 month

Jenkinsfile_CNP, build.gradle, src/functionalTest/java/uk/gov/hmcts/reform/managecase/befta/ManageCaseAssignmentTestAutomationAdapter.java
https://tools.hmcts.net/jira/browse/CCD-2451
Removing jcenter due to [shutdown](https://blog.gradle.org/jcenter-shutdown)
```
[ ] Yes
[ x] No
```
=> Update to build.gradle

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2582
Suppressing CVE-2021-22060
```
[ ] Yes
[X ] No
```
=> Suppressing CVE-2021-22060, CVE-2022-23181, CVE-2021-42550, CVE-2021-44832 

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/CCD-2109
```
[ ] Yes
[X] No
```
=> Updating product_group_name in Ithc branch

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/CCD-2109
```
[ ] Yes
[X] No
```
=> Updating product_group_name in Demo branch

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2691
CWE-862 Suppression
```
[ ] Yes
[X ] No
```
=> Suppression

charts/aac-manage-case-assignment/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-2579
```
[ ] Yes
[ ] No
```
=> Upgrade to Latest Base Helm Charts

build.gradle
https://tools.hmcts.net/jira/browse/CCD-2718
```
[ ] Yes
[ ] No
```
=> Update test definition version to 7.13.0

config/owasp/suppressions.xml
=> --Added suppression for Spring beans jar. This is temporary fix.

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-2921
=> spring shell version update to 5.3.18

config/owasp/suppressions.xml
Suppresion for spring-core-5.3.18.jar relate dependency check failure.
```
[ ] Yes
[ x] No
```
=> Spring-core-5.3.18.jar related suppression

charts/aac-manage-case-assignment/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/CCD-3066
Added civil_service in authorised services for preview env
```
[ ] Yes
[x] No
```
=> CCD-3066: Add civil_service in authorised services for preview env

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3287
Removed suppressions and updated spring-framework.version to 5.3.20
```
[ ] Yes
[X] No
```
=> Removed suppressions and updated spring-framework.version to 5.3.20

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3387
Remove CVE Suppress Until Date from All Services
```
[ ] Yes
[ ] No
```
=> CCD-3387 CVE Suppress Until Date from All Services

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3446
CCD-3446 : Update suppressions.xml (CVE-2022-33915)
```
[ ] Yes
[X] No
```
=> CCD-3446 : Update suppressions.xml (CVE-2022-33915)

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3446
False positive.   CVE-2022-33915 (cpe;2.3;a;apache;log4j) only impacts AWS Log4j hotpatch , and not general Log4j build.   See Jira ticket.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> CCD-3446: CVE-2022-33915 aac-manage-case-assignment

charts/aac-manage-case-assignment/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-3434
Upgrade Java, postgresql and redis configurations
```
[ ] Yes
[x] No
```
=> CCD-3434 upgrade java, postgresql and redis configurations

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3518
CVE-2021-22053
```
[ ] Yes
[ x] No
```
=> CCD-3518 CVE-2021-22053 suppression removed

charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.preview.template.yaml, charts/aac-manage-case-assignment/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/CCD-3566
CCD-3566: Update values.preview.template.yaml (Whitelist private law services in test environments)
```
[ ] Yes
[X] No
```
=> CCD-3566: Whitelist private law services in test environments (application.yaml, values.yaml, preview.yaml)

Jenkinsfile_CNP, charts/aac-manage-case-assignment/values.preview.template.yaml
CCD-3619 (https://tools.hmcts.net/jira/browse/CCD-3619)
Changed values of DEFINITION_STORE_URL_BASE and CCD_DATA_STORE_API_BASE_URL variables used for preview environment in Jenkinsfile_CNP to use https instead of http.
Changed values of CCD_DATA_STORE_API_BASE_URL and CCD_DEFINITION_STORE_API_BASE_URL in values.preview.template.yaml; replaced ".service.core-compute-preview.internal" with "-java.ccd" in both values.
```
[ ] Yes
[x] No
```
=> CCD-3619: Fix preview deployment issues

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-3577
Cleanup CVE Suppressions
```
[ ] Yes
[x ] No
```
=> CCD-3577 cleanup CVE suppressions

config/owasp/suppressions.xml
=> Added CVE suppression

build.gradle, src/functionalTest/resources/features/common/mca/snippets/NoC_Challenge_Questions_Response.td.json, src/main/java/uk/gov/hmcts/reform/managecase/client/definitionstore/model/ChallengeQuestion.java, src/main/java/uk/gov/hmcts/reform/managecase/service/noc/ChallengeAnswerValidator.java, src/test/java/uk/gov/hmcts/reform/managecase/service/noc/ChallengeAnswerValidatorTest.java
https://tools.hmcts.net/jira/browse/CCD-3734
Update validation in Verify NoC Answers to include 
```
[ ] Yes
[ ] No
```
=> CCD-3734 Update validation in Verify NoC Answers to include

src/functionalTest/resources/features/F-205 - Validate NoC Questions/F-205.feature, src/functionalTest/resources/features/common/mca/snippets/NoC_Challenge_Questions_Response.td.json
=> CCD-3734 - FT issues fixed

Jenkinsfile_CNP, Jenkinsfile_nightly, Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/CCD-4050
Fix Jenkins pipeline warnings regarding Groovy after() statements.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> CCD-4050: Fix Jenkins pipeline warnings

Jenkinsfile_CNP, build.gradle
=> Fix pact issue

charts/aac-manage-case-assignment/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-4212
bump java chart to 4.0.8
```
[ ] Yes
[X] No
```
=> bump java chart to 4.0.9

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4313
CVE cleanup.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
=> CCD-4313: CVE cleanup

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4312
CVE-2022-45143 Tomcat Upgrade
```
[ ] Yes
[ x] No
```
=> CCD-4312 CVE-2022-45143 Tomcat Upgrade

charts/aac-manage-case-assignment/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-4317
Upgrade base charts
```
[ ] Yes
[X] No
```
=> CCD-4317 Upgrade base charts

.github/workflows/swagger.yml, .travis.yml, README.md
https://tools.hmcts.net/jira/browse/CCD-4476
CCD-4476 : changed reform-api-docs to cnp-api-docs
```
[ ] Yes
[X] No
```
=> CCD-4476 : changed reform-api-docs to cnp-api-docs

Jenkinsfile_CNP, charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml, src/main/resources/application.yaml
https://tools.hmcts.net/confluence/display/RSTR/ET-Rel-2.1+-+EXUI+legal+Reps+-+Implementation+Plan
Whitelist Employment Tribunals Callbacks API (et_cos) in environment variable 'MANAGE_CASE_S2S_AUTHORISED_SERVICES'.
```
[ ] Yes
[x] No
```
=> Manage case whitelist ET Callbacks API

infrastructure/main.tf
Needed for move to Workload Identity
```
[ ] Yes
[ x] No
```
=> create new managed identity in correct subscription

charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml
https://tools.hmcts.net/jira/browse/DTSPB-3306
probate_backend need to be added to the whitelist for NOC
```
[ ] Yes
[X] No
```
=> DTSPB-3306 probate_backend added to the whitelist

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4949
Fix - Versions below java-logging: 6.0.1
```
[ ] Yes
[ ] No
```
=> CCD-4949:Fix - Versions below java-logging: 6.0.1

charts/aac-manage-case-assignment/Chart.yaml
https://tools.hmcts.net/jira/browse/CCD-4943
Update Helm release java to v5 in all CCD Java Repos
```
[ ] Yes
[x] No
```
=> CCD-4943: Update Helm release java to v5

infrastructure/aat.tfvars
add fpl
```
[ ] Yes
[ ] No
```
=> add fpl to manage identities access

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4970
bumped guava version, removed suppression
```
[ ] Yes
[X] No
```
=> CCD-4970 : Fix CVE-2020-8908

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4962
Fix CVE-2023-20861 and CVE-2023-20860
```
[ ] Yes
[ x] No
```
=> Fix CVE-2023-20861 and CVE-2023-20860

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-4604
removed 20873 as resolved under 20883
```
[ ] Yes
[X] No
```
=> CVE fixes 160124

acb.tpl.yaml, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5045
Add retries to all acb.tpl.yaml entries
```
[ ] Yes
[ x] No
```
=> CCD-5045 : Add retries to all acb.tpl.yaml entries

charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml
https://tools.hmcts.net/jira/browse/NFDIV-3945
=> [NFDIV-3945] Add nfdiv_case_api to whitelist for notice of change

charts/aac-manage-case-assignment/Chart.yaml, charts/aac-manage-case-assignment/values.yaml
=> Updated chart-java 5.0.5 to 5.2.0 chart version from 0.2.14 to 0.2.15

build.gradle, config/owasp/suppressions.xml
Reverts hmcts/aac-manage-case-assignment#545
=> Revert "CCD-5194:"

src/main/resources/application.yaml
https://tools.hmcts.net/jira/browse/CCD-5845
```
[ ] Yes
[ ] No
```
=> CCD-5845 - add et service

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-5158
Upgrade Tomcat to fix CVE
```
[ ] Yes
[x] No
```
=> CCD-5158 - Fix CVE-2023-46589

infrastructure/main.tf, infrastructure/state.tf
https://tools.hmcts.net/jira/browse/CME-306
```
[ ] Yes
[x ] No
```
=> CME-306: Update azurerm

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CFTS-6913
```
[ ] Yes
[ ] No
```
=> CVE FIX: /aac-manage-case-assignment

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6489
Suppressions
```
[ ] Yes
[X] No
```
=> CCD-6489 :: suppress CVE 2024 22259

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6507
Suppress CVE
```
[ ] Yes
[X] No
```
=> CCD-6507 :: Suppress CVE-2024-38808

Jenkinsfile_CNP, aca-docker/compose/aca.yml, build.gradle, src/functionalTest/resources/features/F-206 - Request Notice Of Change/F-206 - Request Notice Of Change.feature, src/functionalTest/resources/features/F-206 - Request Notice Of Change/S-206.07.td.json, src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/verify-case-access-metadata/F-206_Verify_NoC_Request_Access_Metadata.td.json, src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/verify-case-access-metadata/F-206_Verify_NoC_Request_Access_Metadata_Bill.td.json, src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/verify-case-access-metadata/F-206_Verify_NoC_Request_Access_Metadata_Jane.td.json, src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/verify-case-roles/F-206_Verify_Not_Granted_Case_Roles_Bill.td.json, src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/verify-case-roles/F-206_Verify_Not_Granted_Case_Roles_Jane.td.json, src/functionalTest/resources/features/common/data-store/Retrieve_Access_Metadata_By_Case_ID__Base.td.json
=> CCD-6255 FT Tests fro CCD-5334

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/CCD-6624
CCD-6624 :: Suppressions
```
[ ] Yes
[X] No
```
=> CCD-6624 :: Suppressions

build.gradle
NA
Patch, bump befta-fw and ccd-test-definitions to stable versions.
```
[ ] Yes
[X] No
```
=> Patch, bump befta-fw and ccd-test-definitions to stable versions.

Jenkinsfile_CNP, aca-docker/compose/aca.yml, build.gradle, charts/aac-manage-case-assignment/values.preview.template.yaml, src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/case-data-snapshot/F-206_Take_Case_Data_Snapshot__Base.td.json, src/functionalTest/resources/features/F-206 - Request Notice Of Change/common/verify-case-data/F-206_Verify_Case_Data__Base.td.json, src/functionalTest/resources/features/F-209 - Apply NoC Decision/SearchCase/F-209_Search_Case_Case_Data.td.json, src/functionalTest/resources/features/F-209 - Apply NoC Decision/SearchCase/F-209_Search_Case_Data_Classification.td.json, src/functionalTest/resources/features/common/data-store/FT_NoCCaseType/NoC_Case_Creation__Base.td.json, src/functionalTest/resources/features/common/data-store/FT_NoCCaseType/snippets/NoC_Case_Data_Classification__publicFields.td.json, src/functionalTest/resources/features/common/data-store/FT_NoCCaseType/snippets/NoC_Case_Data_With_Org_Policies__publicFields.td.json
=> Ccd 6628 ft failures

Jenkinsfile_CNP, build.gradle
=> Disable pact testing for aac
